### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by kevindente** [bnoguchi/mongoose-auth#102]

**Comment by josefsalyer** [comment]
I have the same question. It doesn't seem that there are many questions being answered here.  Is there a google group?

**Comment by nickpoorman** [comment]
+1

**Comment by rvulpescu** [comment]
+1 There are a few things that need to be updated

**Comment by nleush** [comment]
+1

**Comment by cesine** [comment]
+1

**Comment by lefnire** [comment]
Lotta stale pull requests, last commit 7mo. ago - looks dead. You could always designate the most active amongst you & start using that person's fork as the canonical repo.

**Comment by tthew** [comment]
+1 This is broken out of the box.  Fresh clone of the repo,  `npm install` dependencies then `node example/server`.

Warning from the console: 

```
Warning: express.createServer() is deprecated, express
applications no longer inherit from http.Server,
please use:

    var express = require("express");
    var app = express();

everyauth.helpExpress is being deprecated. helpExpress is now automatically invoked when it detects express. So remove everyauth.helpExpress from your code
```

In the browser:

```
ReferenceError: /Users/somebody/Development/sand/mongoose-auth/example/views/home.jade:1
  > 1| - if (!everyauth.loggedIn)
    2|   h2 Not Authenticated
    3|   #register
    4|     a(href='/register') Register

everyauth is not defined
    at eval (eval at <anonymous> (/Users/somebody/Development/sand/mongoose-auth/node_modules/jade/lib/jade.js:176:8))
    at exports.compile (/Users/somebody/Development/sand/mongoose-auth/node_modules/jade/lib/jade.js:181:12)
    at Object.exports.render (/Users/somebody/Development/sand/mongoose-auth/node_modules/jade/lib/jade.js:216:14)
    at View.exports.renderFile [as engine] (/Users/somebody/Development/sand/mongoose-auth/node_modules/jade/lib/jade.js:243:13)
    at View.render (/Users/somebody/Development/sand/mongoose-auth/node_modules/express/lib/view.js:75:8)
    at Function.app.render (/Users/somebody/Development/sand/mongoose-auth/node_modules/express/lib/application.js:503:10)
    at ServerResponse.res.render (/Users/somebody/Development/sand/mongoose-auth/node_modules/express/lib/response.js:721:7)
    at /Users/somebody/Development/sand/mongoose-auth/example/server.js:111:7
    at callbacks (/Users/somebody/Development/sand/mongoose-auth/node_modules/express/lib/router/index.js:161:37)
    at param (/Users/somebody/Development/sand/mongoose-auth/node_modules/express/lib/router/index.js:135:11)
```

**Comment by NTTAKR** [comment]
Well? Anyone got an answer if this project is still maintained?
