### ISSUE TITLE
Not able to register new user

### ISSUE THREAD

**Issue by DominicBoettger** [bnoguchi/mongoose-auth#113]
When submitting a new user as described in the example.

I get the following exception:

starting step - extractLoginPassword
...finished step
starting step - extractExtraRegistrationParams
...finished step
starting step - aggregateParams
...finished step
starting step - validateRegistrationBase
...finished step
starting step - validateRegistration
TypeError: undefined is not a function
    at Object.module.exports.validateRegistration [as _validateRegistration](/Users/myuser/Development/node/myproject/node_modules/mongoose-auth/lib/modules/password/everyauth.js:28:16)
    at Object.Step.exec (/Users/myuser/Development/node/myproject/node_modules/everyauth/lib/step.js:47:21)
    at StepSequence._bind (/Users/myuser/Development/node/myproject/node_modules/everyauth/lib/stepSequence.js:26:38)
    at Promise.callback (/Users/myuser/Development/node/myproject/node_modules/everyauth/lib/promise.js:13:12)
    at RouteTriggeredSequence.StepSequence._bind (/Users/myuser/Development/node/myproject/node_modules/everyauth/lib/stepSequence.js:25:20)
    at RouteTriggeredSequence.StepSequence.start (/Users/myuser/Development/node/myproject/node_modules/everyauth/lib/stepSequence.js:52:33)
    at RouteTriggeredSequence.routeHandler (/Users/myuser/Development/node/myproject/node_modules/everyauth/lib/routeTriggeredSequence.js:13:13)
    at nextMiddleware (/Users/myuser/Development/node/myproject/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:175:25)
    at param (/Users/myuser/Development/node/myproject/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:183:17)
    at pass (/Users/myuser/Development/node/myproject/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:191:11)

**Comment by DominicBoettger** [comment]
Solved this Issue. Global variable User was set to wrong mongoose model.
