### ISSUE TITLE
Installation fails on Linux64

### ISSUE THREAD

**Issue by jamlfy** [bnoguchi/mongoose-auth#123]
Installation in Linux64 is failing, through NPM. Here is the error

``` console
$ sudo npm install mongoose-auth
npm http GET https://registry.npmjs.org/mongoose-auth
npm http 304 https://registry.npmjs.org/mongoose-auth
npm http GET https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/everyauth
npm http 304 https://registry.npmjs.org/everyauth
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/request
npm http GET https://github.com/ciaranj/node-oauth/tarball/master
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/openid
npm http GET https://registry.npmjs.org/xml2js
npm http GET https://registry.npmjs.org/node-swt
npm http GET https://registry.npmjs.org/node-wsfederation
npm http GET https://registry.npmjs.org/debug/0.5.0
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/bindings/1.0.0
npm WARN package.json connect@1.9.2 No README.md file found!
npm http 304 https://registry.npmjs.org/request

> bcrypt@0.7.3 install /home/thor/Area de Trabajo/node_modules/mongoose-auth/node_modules/bcrypt
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/openid
npm http 304 https://registry.npmjs.org/node-swt
npm WARN package.json node-swt@0.1.1 No README.md file found!
npm http 304 https://registry.npmjs.org/node-wsfederation
npm WARN package.json node-wsfederation@0.1.1 No README.md file found!
npm http 304 https://registry.npmjs.org/xml2js
npm http 304 https://registry.npmjs.org/debug/0.5.0
make: se ingresa al directorio «/home/thor/Area de Trabajo/node_modules/mongoose-auth/node_modules/bcrypt/build»
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: No se encontró el programa
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: se sale del directorio «/home/thor/Area de Trabajo/node_modules/mongoose-auth/node_modules/bcrypt/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:232:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.5.0-19-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/thor/Area de Trabajo/node_modules/mongoose-auth/node_modules/bcrypt
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.8.1
gyp ERR! not ok 
npm ERR! bcrypt@0.7.3 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.5.0-19-generic
npm ERR! command "nodejs" "/usr/bin/npm" "install" "mongoose-auth"
npm ERR! cwd /home/thor/Area de Trabajo
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code ELIFECYCLE
npm http 200 https://github.com/ciaranj/node-oauth/tarball/master
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/formidable
npm http 304 https://registry.npmjs.org/formidable
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/sax
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/thor/Area de Trabajo/npm-debug.log
npm ERR! not ok code 0
```

Any solution??

**Comment by wlepinski** [comment]
I'm having the same problem on OSX 10.8.2.

**Comment by jamlfy** [comment]
The problem is a library that requires a compiler g++, if you are not always going to generate the error. It is best to place a note in installation of that package.
