### ISSUE TITLE
Catch exception on timeout

### ISSUE THREAD

**Issue by ghost** [bnoguchi/mongoose-auth#24]
Hi - I often get this error when authenticating with facebook:

```
Error: Step getAccessToken of `facebook` module timed out.
    at /usr/local/tixelated/node_modules/mongoose-auth/node_modules/everyauth/lib/step.js:101:18
    at Object.<anonymous> (/usr/local/tixelated/node_modules/mongoose-auth/node_modules/everyauth/lib/promise.js:63:27)
    at Timer.callback (timers.js:62:39)
```

I've read the advice about increasing the timeout value, but am looking for some advice on the recommended way to catch this exception (more of a node question than auth question I guess.) It crashes node entirely when it occurs...

**Comment by bnoguchi** [comment]
I just added a way for you to configure error handling in `everyauth`. Install the latest `everyauth`, and then in `mongoose-auth`:

``` javascript
UserSchema.plugin(mongooseAuth, {
        everymodule: {
          everyauth: {
              User: function () {
                return User;
              }
            , moduleErrback: function (err) {
                // Do what you want with your error.
                // Timeouts pass an error that get intercepted by your function defined here.
              }
          }
        }
      , //...
    });
```

--Brian
