### ISSUE TITLE
'mongoose-types' dependency?

### ISSUE THREAD

**Issue by busticated** [bnoguchi/mongoose-auth#3]
Looks like there's a dependency declaration missing from package.json? I'm getting the following error after requiring "mongoose-auth":

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'mongoose-types'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/mongoose-auth/0.0.5/package/lib/modules/facebook/schema.js:2:21)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/mongoose-auth/0.0.5/package/lib/modules/facebook/index.js:1:80)

**Comment by bnoguchi** [comment]
Thanks for the heads up. Just updated package.json to include the mongoose-types dependency. Do an uninstall first, then an install

```
$ npm uninstall mongoose-auth
$ npm install mongoose-auth
```
