### ISSUE TITLE
TypeError: Object function String() { [native code] } has no method 'get'

### ISSUE THREAD

**Issue by dtan** [bnoguchi/mongoose-auth#31]
I keep on getting this error when i try to include mongoose-auth and then use the password plugin:

TypeError: Object function String() { [native code] } has no method 'get'
    at /site/node_modules/mongoose-auth/lib/modules/password/plugin.js:35:30
    at /site/node_modules/mongoose-auth/index.js:73:5
    at Array.forEach (native)
    at plugin (/site/node_modules/mongoose-auth/index.js:36:6)
    at Schema.plugin (/site/node_modules/mongoose/lib/mongoose/schema.js:289:3)
    at Object.<anonymous> (/site/site/models/Users.js:27:7)
    at Module._compile (module.js:407:26)
    at module.js:413:10
    at Object..js (/usr/local/lib/node_modules/node-dev/wrapper.js:59:5)
    at Module.load (module.js:339:31)

any clues on what is causing this?

**Comment by dtan** [comment]
also, when i try and use the mongooseAuth.middleware() inside my express app, i get this error:

TypeError: Object function plugin(schema, opts) {
....  a bunch of code ....
  exports.helpExpress = everyauth.helpExpress.bind(everyauth);
} has no method 'middleware'
    at Object.<anonymous> (/site/app.js:34:20)
    at Module._compile (module.js:407:26)
    at module.js:413:10
    at Object..js (/usr/local/lib/node_modules/node-dev/wrapper.js:59:5)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:351:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-dev/wrapper.js:69:1)
    at Module._compile (module.js:407:26)
    at Object.<anonymous> (module.js:413:10)

I think i forgot to put in the middleware so I was getting the error above, but after putting in the middleware (and commenting out my app.router middleware) this is what occurs.

**Comment by bnoguchi** [comment]
Can you create a [gist](https://gist.github.com/), so I can re-create this issue?

**Comment by dtan** [comment]
well, i found out the reason for the original issue - i had `password: String` in my schema.  Taking that out makes it work fine.  Though I can't seem to reproduce the second error.  However, I am having trouble breaking this up onto multiple files.  I can't seem to `submit` and redirect.  I basically followed the example server.js file, which worked when i left it all on in one file.  is there an example of how this can be accomplished?

**Comment by vikstrous** [comment]
I had the same issue. This helped. It would be a nice if the error was more descriptive.
