### ISSUE TITLE
Cannot register with password authentication

### ISSUE THREAD

**Issue by mrryanjohnston** [bnoguchi/mongoose-auth#35]
When attempting to use the password authentication (using the example application provided with module after removing `loginWith: 'email'` line), the following error occurs:

TypeError: Cannot read property 'sanitize' of undefined
    at Object._validateRegistrationBase (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/lib/modules/password.js:284:40)
    at Object.exec (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/lib/step.js:48:21)
    at /home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/lib/stepSequence.js:19:38
    at [object Object].callback (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/lib/promise.js:13:12)
    at RouteTriggeredSequence._bind (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/lib/stepSequence.js:18:20)
    at RouteTriggeredSequence.start (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/lib/stepSequence.js:45:33)
    at RouteTriggeredSequence.routeHandler (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/lib/routeTriggeredSequence.js:16:13)
    at Object.<anonymous> (native)
    at nextMiddleware (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:175:25)
    at param (/home/ryan/git/mongoose-auth/node_modules/mongoose-auth/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:183:16)

**Comment by mrryanjohnston** [comment]
Found another user having this problem in IRC backlogs here:

http://nodejs.debuggable.com/2011-08-01.txt

Look for user "greg__"

**Comment by mrryanjohnston** [comment]
Output when trying it out on cloud9ide

Go to http://local.host:3000
starting step - extractLoginPassword
...finished step
starting step - extractExtraRegistrationParams
...finished step
starting step - aggregateParams
...finished step
starting step - validateRegistrationBase
TypeError: Cannot read property 'sanitize' of undefined
    at Object._validateRegistrationBase (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/lib/modules/password.js:284:40)
    at Object.exec (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/lib/step.js:48:21)
    at /mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/lib/stepSequence.js:19:38
    at [object Object].callback (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/lib/promise.js:13:12)
    at RouteTriggeredSequence._bind (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/lib/stepSequence.js:18:20)
    at RouteTriggeredSequence.start (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/lib/stepSequence.js:45:33)
    at RouteTriggeredSequence.routeHandler (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/lib/routeTriggeredSequence.js:16:13)
    at Object. (native)
    at nextMiddleware (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:175:25)
    at param (/mnt/ws/users/mrryanjohnston/66683/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:183:16)

**Comment by mrryanjohnston** [comment]
After commenting out line 284 and lines 290-296, registration works. However, sanitation and validation are both removed with this patch and is not favorable (obviously).

**Comment by mrryanjohnston** [comment]
Fixed. everyauth.password.loginWith('login') must be explicitly specified. I thought it could be left out. Perhaps documentation should be changed a bit?
