### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by Shakakai** [bnoguchi/mongoose-auth#40]
I just tried to install mongoose-auth via NPM and received this error. Have you seen this issue before?

npm info uninstall sax@0.2.3 complete
npm info uninstall oauth@0.9.5 complete
npm info uninstall mongoose-types@1.0.3 complete
npm info uninstall everyauth@0.2.18 complete
npm info uninstall mongoose-auth@0.0.11 complete
npm info install failed rolled back
npm ERR! Error: bcrypt@0.2.4 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.3.15/package/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:45:17)
npm ERR!     at ChildProcess.onexit (child_process.js:171:12)
npm ERR! 
npm ERR! Failed at the bcrypt@0.2.4 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 11.1.0
npm ERR! argv { remain: 
npm ERR! argv    [ 'mongoose-auth',
npm ERR! argv      'bcrypt@>=0.2.0',
npm ERR! argv      'mongoose@>=1.4.0',
npm ERR! argv      'everyauth@>=0.2.11',
npm ERR! argv      'mongoose-types@>=1.0.3',
npm ERR! argv      'oauth@>=0.9.0',
npm ERR! argv      'restler@>=0.2.1',
npm ERR! argv      'connect@>=1.4.0',
npm ERR! argv      'openid@=0.1.8',
npm ERR! argv      'xml2js@>=0.1.7',
npm ERR! argv      'mongoose@>= 1.0.16',
npm ERR! argv      'sax@>=0.1.1' ],
npm ERR! argv   cooked: [ 'install', 'mongoose-auth' ],
npm ERR! argv   original: [ 'install', 'mongoose-auth' ] }
npm not ok

**Comment by arajendiran** [comment]
I am having the same issue.
