### ISSUE TITLE
Error: You have not defined a path for the route alias getLoginPath.

### ISSUE THREAD

**Issue by ghost** [bnoguchi/mongoose-auth#50]
I'm testing a node.js app I'm writing when I get the following error. I'm not sure what to do about it since there' nothing in the example. I suspect the error is on my side since I'm so new to node.
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: You have not defined a path for the route alias getLoginPath.
    at Object.routeApp (/home/levi/Projects/Cloudrr/node_modules/mongoose-auth/node_modules/everyauth/lib/modules/everymodule.js:240:19)
    at Function.<anonymous> (/home/levi/Projects/Cloudrr/node_modules/mongoose-auth/node_modules/everyauth/index.js:56:19)
    at Function.router (/home/levi/Projects/Cloudrr/node_modules/mongoose-auth/node_modules/everyauth/node_modules/connect/lib/middleware/router.js:96:6)
    at Object.middleware (/home/levi/Projects/Cloudrr/node_modules/mongoose-auth/node_modules/everyauth/index.js:50:15)
    at Function.middleware (native)
    at Object.<anonymous> (/home/levi/Projects/Cloudrr/app.js:12:20)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)

my app.js, models.js, and package.json are available at https://gist.github.com/1294116
Thank you for your time.

**Comment by psugihara** [comment]
Did you figure out the solution to this?

**Comment by gagandeep** [comment]
Did anyone figure out solution?
