### ISSUE TITLE
Exception with Google

### ISSUE THREAD

**Issue by kevindente** [bnoguchi/mongoose-auth#79]
I tried integrating mongoose-auth into my app using the Google provider. It works until the callback, when I get an exception

TypeError: Cannot call method 'match' of undefined
    at /Users/kevind/Documents/NodeApps/gtp/node_modules/mongoose-auth/node_modules/everyauth/lib/modules/google.js:47:32
    at /Users/kevind/Documents/NodeApps/gtp/node_modules/mongoose-auth/node_modules/everyauth/lib/step.js:98:21

The exception comes out of the .convertErr step, which is calling .match on the property data.data, and there is no data.data field.  At first I thought it was how I was using it, but I tried the example app and got the same exception.

**Comment by kevindente** [comment]
I should add I'm unclear if this is an issue in Mongoose-auth or everyauth. Let me know if I should report it elsewhere.
