### ISSUE TITLE
registration error

### ISSUE THREAD

**Issue by csanz** [bnoguchi/mongoose-auth#9]
Hey Brian, I'll look into it later on to see if I can fix, but wanted to send you this right away, just in case you knew about it already. 

$ node example/server.js 
starting step - displayRegister
starting step - extractLoginPassword
...finished step
starting step - registerUser

/mongoose-auth/node_modules/.npm/everyauth/0.1.6/package/lib/sequence.js:90
        throw err;
        ^
Error: Step registerUser of `password` module timed out.
    at /mongoose-auth/node_modules/.npm/everyauth/0.1.6/package/lib/sequence.js:105:18
    at Object.<anonymous> (/mongoose-auth/node_modules/.npm/everyauth/0.1.6/package/lib/promise.js:62:27)
    at Timer.callback (timers.js:83:39)

**Comment by csanz** [comment]
never mind! friggin mongod was stopped.
